const questions = [
  "Who do you aspire to be like?",
  "What is your greatest fear?",
  "What is something that is difficult for you to remember?",
  "What do you think everyone should learn?",
  "What is the most spontaneous thing you have ever done?",
  "What is a skill you wish you had learned earlier in life?",
  "What would you do with an unexpected free day?",
  "What is your most unpopular opinion?",
  "What fictional world would you most want to live in?",
  "What is the best piece of advice you have ever received?",
  "What habit are you most proud of breaking?",
  "What is something you used to believe that you no longer do?",
  "If you could have dinner with anyone, living or dead, who would it be?",
  "What is something most people do not know about you?",
  "What would you want your last meal to be?",
  "What is your most irrational fear?",
  "What childhood memory do you treasure most?",
  "What is a decision you made that changed your life?",
  "What is something you have changed your mind about recently?",
  "What is the most meaningful gift you have ever received?",
  "What is something you find beautiful that others might not notice?",
  "What would you do if you knew you could not fail?",
  "What is something you have always wanted to try but have not yet?",
  "What is your favorite thing about where you grew up?",
  "What is a talent you have that surprises people?",
  "What would you tell your 10-year-old self?",
  "What is the most important thing in a friendship?",
  "What is a movie or book that genuinely changed how you see the world?",
  "What small thing consistently makes your day better?",
  "What is something you are secretly competitive about?",
  "What is the hardest lesson life has taught you?",
  "If you could only keep three possessions, what would they be?",
  "What accomplishment are you most proud of?",
  "What do you think is the most overrated thing in life?",
  "What is something you do differently than most people?",
  "What is a question you wish people would ask you more?",
  "What is the strangest dream you can remember?",
  "What is your love language?",
  "What is something you regret not starting sooner?",
  "What does success mean to you?",
  "What is something you admire in others but struggle with yourself?",
  "What is the best risk you ever took?",
  "What is the most important thing you do for your mental health?",
  "If you could be an expert in anything instantly, what would it be?",
  "What superpower would you choose and why?",
  "What is something that once scared you but no longer does?",
  "What is a cause you care deeply about?",
  "What is the weirdest food combination you actually enjoy?",
  "What is the last thing that made you genuinely laugh out loud?",
  "What is something about yourself that you are still trying to understand?",
  "What era of history would you most want to visit?",
  "What is something you think is worth doing slowly?",
  "If you had to move to another country, where would you go?",
  "What is something you pretend to understand but actually do not?",
  "What would the title of your memoir be?",
  "What is one thing you want to accomplish before you die?",
  "What is something you have strong opinions about that surprises people?",
  "What is the most interesting job you could imagine having?",
  "What do you need more of in your life right now?",
  "What is your most used emoji and why does it represent you?",
  "What are you better at than you give yourself credit for?",
  "What is something you miss that no longer exists?",
  "What is the most interesting place you have ever visited?",
  "What is your earliest memory?",
  "What is a question you have never found a satisfying answer to?",
  "What is something you are genuinely curious about right now?",
  "What do you think is the biggest problem in the world?",
  "What is your favorite way to spend time alone?",
  "What is one thing you would change about how you were raised?",
  "What is the most surprising thing about adulthood?",
  "What is something you are looking forward to?",
  "What is a rule you always try to live by?",
  "What is something that consistently restores your energy?",
  "What is a subject you could teach a class on?",
  "What is the kindest thing anyone has ever done for you?",
  "What is your most treasured tradition?",
  "What would your friends say is your most defining trait?",
  "What is something you used to be embarrassed about that you are now proud of?",
  "What is a compliment that has stuck with you for years?",
  "What is something you are glad you did even though it was difficult?",
  "What is one thing technology cannot replace for you?",
  "What is something you would do even if you were never paid for it?",
  "What is the most interesting conversation you have ever had?",
  "What do you think people misunderstand about you?",
  "What is something you believe that most people around you do not?",
  "What is a place that feels like home that is not your home?",
  "What is your most reliable comfort food?",
  "What is a song that always puts you in a good mood?",
  "What is something you have made with your own hands that you are proud of?",
  "What is your philosophy on money?",
  "What is one thing you wish you could say to someone you have lost touch with?",
  "What is something you want to be remembered for?",
  "What is an assumption people often make about you that is wrong?",
  "What is something that is harder than it looks?",
  "What is the most valuable thing you have learned from a failure?",
  "What is a weird way you are superstitious?",
  "What is something you have tried once and would never do again?",
  "What is something you hope never changes?",
  "What is the first thing you notice about a person?",
];

export default questions;
